/**
 * Every sound cue the app can play. Files live in public/sounds and are generated by
 * scripts/generate-sfx.mjs, so they share one design language; add a cue there first.
 *
 * `gain` is the cue's own level (the user's master volume sits on top); `minGapMs` stops the
 * same cue from stuttering when a state change fires several times in a row.
 */
export const SFX = {
  create: { gain: 0.9, minGapMs: 400 },
  save: { gain: 0.45, minGapMs: 4000 },
  success: { gain: 0.9, minGapMs: 500 },
  check: { gain: 0.8, minGapMs: 150 },
  "task-complete": { gain: 1, minGapMs: 500 },
  delete: { gain: 0.9, minGapMs: 500 },
  restore: { gain: 0.9, minGapMs: 500 },
  notification: { gain: 1, minGapMs: 3000 },
  error: { gain: 0.9, minGapMs: 1500 },
  connect: { gain: 1, minGapMs: 1000 },
  disconnect: { gain: 0.9, minGapMs: 1000 },
  "ai-start": { gain: 0.7, minGapMs: 2000 },
  "ai-done": { gain: 0.85, minGapMs: 1000 },
} as const;

export type SfxName = keyof typeof SFX;

export interface SoundPreference {
  enabled: boolean;
  /** Master volume 0–1. */
  volume: number;
}

export const DEFAULT_SOUND: SoundPreference = { enabled: true, volume: 0.6 };
